post:
    path:     /
    defaults: { _controller: "AppBundle:Post:index" }

post_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:Post:show" }

post_new:
    path:     /new
    defaults: { _controller: "AppBundle:Post:new" }

post_create:
    path:     /create
    defaults: { _controller: "AppBundle:Post:create" }
    methods:  POST

post_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:Post:edit" }

post_update:
    path:     /update/{id}
    defaults: { _controller: "AppBundle:Post:update" }
    methods:  [POST, PUT]

post_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:Post:delete" }
    methods:  [POST, DELETE]
