app_post:
    resource: "@AppBundle/Resources/config/routing/post.yml"
    prefix:   /manage/post

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /manage/user

dashboard:
    path: /dashboard
    defaults: { _controller: "AppBundle:Dashboard:index"}

post_list:
    path: /
    defaults: { _controller: "AppBundle:Blog:index"}

post_details:
    path: /post/{id}
    defaults: { _controller: "AppBundle:Blog:post"}

post_comment:
    path: /post/comment/{postId}
    defaults: { _controller: "AppBundle:Blog:postComment"}

login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    pattern: /logout
    requirements:
      _scheme:  http